name: amway-bee-safe-us

services:
  frontend:
    build:
      context: ../..
      dockerfile: Docker/production-us/Dockerfile
    image: bee_safe_frontend
    container_name: bee_safe_frontend
    ports:
      - "8080:80"
    networks:
      - amway-bee-safe-us_default
    restart: always

networks:
  amway-bee-safe-us_default:
    external: true
