name: "amway-bee-safe-my"

volumes:
  postgres_data: {}
  postgres_data_backups: {}
  traefik: {}
  django_media: {}
  redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    volumes:
      - django_media:/app/bee_safe/media
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production-my/.django
      - ./.envs/.production-my/.postgres
    command: /start
    networks:
      - amway-bee-safe-my
    restart: unless-stopped

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_data_backups:/backups
    env_file:
      - ./.envs/.production-my/.postgres
    command: postgres -c max_connections=1000 -c shared_buffers=512MB -c work_mem=16MB -c effective_cache_size=2GB
    networks:
      - amway-bee-safe-my
    restart: unless-stopped

  pgbouncer:
    image: edoburu/pgbouncer
    ports:
      - "6432:6432"
    env_file:
      - ./.envs/.production-my/.postgres
    depends_on:
      - postgres
    networks:
      - amway-bee-safe-my
    restart: unless-stopped

  traefik:
    build:
      context: .
      dockerfile: ./compose/production-my/traefik/Dockerfile
    depends_on:
      - django
    volumes:
      - traefik:/etc/traefik/acme
    ports:
      - "0.0.0.0:8081:80"
    networks:
      - amway-bee-safe-my
    restart: unless-stopped

  redis:
    image: docker.io/redis:6
    volumes:
      - redis_data:/data
    networks:
      - amway-bee-safe-my
    restart: unless-stopped

  celeryworker:
    <<: *django
    command: /start-celeryworker
    networks:
      - amway-bee-safe-my
    restart: unless-stopped

  celerybeat:
    <<: *django
    command: /start-celerybeat
    networks:
      - amway-bee-safe-my
    restart: unless-stopped

  flower:
    <<: *django
    command: /start-flower
    networks:
      - amway-bee-safe-my
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    depends_on:
      - django
    volumes:
      - django_media:/usr/share/nginx/media:ro
    networks:
      - amway-bee-safe-my

networks:
  amway-bee-safe-my:
    driver: bridge
