services:
  docs:
    image: bee_safe_local_docs
    container_name: bee_safe_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./bee_safe:/app/bee_safe:z
    ports:
      - "9000:9000"
    command: /start-docs
