volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}

  production_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: bee_safe_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    restart: unless-stopped

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: bee_safe_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres
    command: postgres -c max_connections=1000 -c shared_buffers=512MB -c work_mem=16MB -c effective_cache_size=2GB
    restart: unless-stopped

  pgbouncer:
    image: edoburu/pgbouncer
    container_name: pgbouncer
    ports:
      - "6432:6432"
    env_file:
      - ./.envs/.production/.postgres
    depends_on:
      - postgres
    restart: unless-stopped

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: bee_safe_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    restart: unless-stopped

  redis:
    image: docker.io/redis:6
    volumes:
      - production_redis_data:/data
    restart: unless-stopped

  celeryworker:
    <<: *django
    image: bee_safe_production_celeryworker
    command: /start-celeryworker
    restart: unless-stopped

  celerybeat:
    <<: *django
    image: bee_safe_production_celerybeat
    command: /start-celerybeat
    restart: unless-stopped

  flower:
    <<: *django
    image: bee_safe_production_flower
    command: /start-flower
    restart: unless-stopped
