# Generated by Django 5.2.4 on 2025-09-16 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(unique=True)),
            ],
            options={
                'verbose_name': 'Key',
                'verbose_name_plural': 'Keys',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, default='')),
                ('text_en', models.TextField(blank=True, default='', null=True)),
                ('text_ru', models.TextField(blank=True, default='', null=True)),
                ('text_zh_hans', models.TextField(blank=True, default='', null=True)),
                ('text_zh_hant', models.TextField(blank=True, default='', null=True)),
                ('text_ja', models.TextField(blank=True, default='', null=True)),
                ('text_ko', models.TextField(blank=True, default='', null=True)),
                ('text_es', models.TextField(blank=True, default='', null=True)),
                ('text_pt', models.TextField(blank=True, default='', null=True)),
                ('text_th', models.TextField(blank=True, default='', null=True)),
                ('text_vi', models.TextField(blank=True, default='', null=True)),
                ('text_ind', models.TextField(blank=True, default='', null=True)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text', to='texts.key')),
            ],
            options={
                'verbose_name': 'Text',
                'verbose_name_plural': 'Texts',
                'abstract': False,
            },
        ),
    ]
