# Generated by Django 5.2.4 on 2025-09-16 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
