# Generated by Django 5.2.4 on 2025-07-24 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def create_answer_texts(apps, schema_editor):
    Text = apps.get_model('quizzes', 'Text')
    Text.objects.get_or_create(key="right_answer", text="Yeah! You got it correct!")
    Text.objects.get_or_create(key="wrong_answer", text="Nope. Try again.")

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(verbose_name='Question text')),
                ('text_en', models.TextField(null=True, verbose_name='Question text')),
                ('text_ru', models.TextField(null=True, verbose_name='Question text')),
                ('text_zh_hans', models.TextField(null=True, verbose_name='Question text')),
                ('text_zh_hant', models.TextField(null=True, verbose_name='Question text')),
                ('text_ja', models.TextField(null=True, verbose_name='Question text')),
                ('text_ko', models.TextField(null=True, verbose_name='Question text')),
                ('text_es', models.TextField(null=True, verbose_name='Question text')),
                ('text_pt', models.TextField(null=True, verbose_name='Question text')),
                ('text_th', models.TextField(null=True, verbose_name='Question text')),
                ('text_vi', models.TextField(null=True, verbose_name='Question text')),
                ('text_ind', models.TextField(null=True, verbose_name='Question text')),
                ('question_type', models.CharField(choices=[('MCQ', 'MCQ'), ('MATCH', 'Match option pairs')])),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(unique=True)),
                ('text', models.TextField(blank=True, default='')),
                ('text_en', models.TextField(blank=True, default='', null=True)),
                ('text_ru', models.TextField(blank=True, default='', null=True)),
                ('text_zh_hans', models.TextField(blank=True, default='', null=True)),
                ('text_zh_hant', models.TextField(blank=True, default='', null=True)),
                ('text_ja', models.TextField(blank=True, default='', null=True)),
                ('text_ko', models.TextField(blank=True, default='', null=True)),
                ('text_es', models.TextField(blank=True, default='', null=True)),
                ('text_pt', models.TextField(blank=True, default='', null=True)),
                ('text_th', models.TextField(blank=True, default='', null=True)),
                ('text_vi', models.TextField(blank=True, default='', null=True)),
                ('text_ind', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'verbose_name': 'Text',
                'verbose_name_plural': 'Texts',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MCQOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(verbose_name='Option text')),
                ('text_en', models.CharField(null=True, verbose_name='Option text')),
                ('text_ru', models.CharField(null=True, verbose_name='Option text')),
                ('text_zh_hans', models.CharField(null=True, verbose_name='Option text')),
                ('text_zh_hant', models.CharField(null=True, verbose_name='Option text')),
                ('text_ja', models.CharField(null=True, verbose_name='Option text')),
                ('text_ko', models.CharField(null=True, verbose_name='Option text')),
                ('text_es', models.CharField(null=True, verbose_name='Option text')),
                ('text_pt', models.CharField(null=True, verbose_name='Option text')),
                ('text_th', models.CharField(null=True, verbose_name='Option text')),
                ('text_vi', models.CharField(null=True, verbose_name='Option text')),
                ('text_ind', models.CharField(null=True, verbose_name='Option text')),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(limit_choices_to={'question_type': 'MCQ'}, on_delete=django.db.models.deletion.CASCADE, related_name='mcq_options', to='quizzes.question')),
            ],
            options={
                'verbose_name': 'MCQ option',
                'verbose_name_plural': 'MCQ options',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_score', models.IntegerField(default=200, verbose_name='Base score')),
                ('seconds_spent', models.IntegerField(default=0, verbose_name='Seconds spent')),
                ('wrong_count', models.IntegerField(default=0, verbose_name='Wrong count')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Is correct')),
                ('score', models.IntegerField(default=0, verbose_name='Score')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.question', verbose_name='Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Quiz question',
                'verbose_name_plural': 'Quiz questions',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatchOptionPair',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option_a', models.CharField(verbose_name='Left side')),
                ('option_a_en', models.CharField(null=True, verbose_name='Left side')),
                ('option_a_ru', models.CharField(null=True, verbose_name='Left side')),
                ('option_a_zh_hans', models.CharField(null=True, verbose_name='Left side')),
                ('option_a_zh_hant', models.CharField(null=True, verbose_name='Left side')),
                ('option_a_ja', models.CharField(null=True, verbose_name='Left side')),
                ('option_a_ko', models.CharField(null=True, verbose_name='Left side')),
                ('option_a_es', models.CharField(null=True, verbose_name='Left side')),
                ('option_a_pt', models.CharField(null=True, verbose_name='Left side')),
                ('option_a_th', models.CharField(null=True, verbose_name='Left side')),
                ('option_a_vi', models.CharField(null=True, verbose_name='Left side')),
                ('option_a_ind', models.CharField(null=True, verbose_name='Left side')),
                ('option_b', models.CharField(verbose_name='Right side')),
                ('option_b_en', models.CharField(null=True, verbose_name='Right side')),
                ('option_b_ru', models.CharField(null=True, verbose_name='Right side')),
                ('option_b_zh_hans', models.CharField(null=True, verbose_name='Right side')),
                ('option_b_zh_hant', models.CharField(null=True, verbose_name='Right side')),
                ('option_b_ja', models.CharField(null=True, verbose_name='Right side')),
                ('option_b_ko', models.CharField(null=True, verbose_name='Right side')),
                ('option_b_es', models.CharField(null=True, verbose_name='Right side')),
                ('option_b_pt', models.CharField(null=True, verbose_name='Right side')),
                ('option_b_th', models.CharField(null=True, verbose_name='Right side')),
                ('option_b_vi', models.CharField(null=True, verbose_name='Right side')),
                ('option_b_ind', models.CharField(null=True, verbose_name='Right side')),
                ('question', models.ForeignKey(limit_choices_to={'question_type': 'MATCH'}, on_delete=django.db.models.deletion.CASCADE, related_name='match_pairs', to='quizzes.question')),
            ],
            options={
                'verbose_name': 'Match option pair',
                'verbose_name_plural': 'Match option pairs',
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('question', 'option_a', 'option_b'), name='unique_match_pair_forward'), models.UniqueConstraint(fields=('question', 'option_b', 'option_a'), name='unique_match_pair_reverse'), models.UniqueConstraint(fields=('question', 'option_a', 'option_b_en'), name='unique_match_pair_forward-option_b_en'), models.UniqueConstraint(fields=('question', 'option_a', 'option_b_ru'), name='unique_match_pair_forward-option_b_ru'), models.UniqueConstraint(fields=('question', 'option_a', 'option_b_zh_hans'), name='unique_match_pair_forward-option_b_zh_hans'), models.UniqueConstraint(fields=('question', 'option_a', 'option_b_zh_hant'), name='unique_match_pair_forward-option_b_zh_hant'), models.UniqueConstraint(fields=('question', 'option_a', 'option_b_ja'), name='unique_match_pair_forward-option_b_ja'), models.UniqueConstraint(fields=('question', 'option_a', 'option_b_ko'), name='unique_match_pair_forward-option_b_ko'), models.UniqueConstraint(fields=('question', 'option_a', 'option_b_es'), name='unique_match_pair_forward-option_b_es'), models.UniqueConstraint(fields=('question', 'option_a', 'option_b_pt'), name='unique_match_pair_forward-option_b_pt'), models.UniqueConstraint(fields=('question', 'option_a', 'option_b_th'), name='unique_match_pair_forward-option_b_th'), models.UniqueConstraint(fields=('question', 'option_a', 'option_b_vi'), name='unique_match_pair_forward-option_b_vi'), models.UniqueConstraint(fields=('question', 'option_a', 'option_b_ind'), name='unique_match_pair_forward-option_b_ind'), models.UniqueConstraint(fields=('question', 'option_a_en', 'option_b'), name='unique_match_pair_forward-option_a_en'), models.UniqueConstraint(fields=('question', 'option_a_ru', 'option_b'), name='unique_match_pair_forward-option_a_ru'), models.UniqueConstraint(fields=('question', 'option_a_zh_hans', 'option_b'), name='unique_match_pair_forward-option_a_zh_hans'), models.UniqueConstraint(fields=('question', 'option_a_zh_hant', 'option_b'), name='unique_match_pair_forward-option_a_zh_hant'), models.UniqueConstraint(fields=('question', 'option_a_ja', 'option_b'), name='unique_match_pair_forward-option_a_ja'), models.UniqueConstraint(fields=('question', 'option_a_ko', 'option_b'), name='unique_match_pair_forward-option_a_ko'), models.UniqueConstraint(fields=('question', 'option_a_es', 'option_b'), name='unique_match_pair_forward-option_a_es'), models.UniqueConstraint(fields=('question', 'option_a_pt', 'option_b'), name='unique_match_pair_forward-option_a_pt'), models.UniqueConstraint(fields=('question', 'option_a_th', 'option_b'), name='unique_match_pair_forward-option_a_th'), models.UniqueConstraint(fields=('question', 'option_a_vi', 'option_b'), name='unique_match_pair_forward-option_a_vi'), models.UniqueConstraint(fields=('question', 'option_a_ind', 'option_b'), name='unique_match_pair_forward-option_a_ind'), models.UniqueConstraint(fields=('question', 'option_b_en', 'option_a'), name='unique_match_pair_reverse-option_b_en'), models.UniqueConstraint(fields=('question', 'option_b_ru', 'option_a'), name='unique_match_pair_reverse-option_b_ru'), models.UniqueConstraint(fields=('question', 'option_b_zh_hans', 'option_a'), name='unique_match_pair_reverse-option_b_zh_hans'), models.UniqueConstraint(fields=('question', 'option_b_zh_hant', 'option_a'), name='unique_match_pair_reverse-option_b_zh_hant'), models.UniqueConstraint(fields=('question', 'option_b_ja', 'option_a'), name='unique_match_pair_reverse-option_b_ja'), models.UniqueConstraint(fields=('question', 'option_b_ko', 'option_a'), name='unique_match_pair_reverse-option_b_ko'), models.UniqueConstraint(fields=('question', 'option_b_es', 'option_a'), name='unique_match_pair_reverse-option_b_es'), models.UniqueConstraint(fields=('question', 'option_b_pt', 'option_a'), name='unique_match_pair_reverse-option_b_pt'), models.UniqueConstraint(fields=('question', 'option_b_th', 'option_a'), name='unique_match_pair_reverse-option_b_th'), models.UniqueConstraint(fields=('question', 'option_b_vi', 'option_a'), name='unique_match_pair_reverse-option_b_vi'), models.UniqueConstraint(fields=('question', 'option_b_ind', 'option_a'), name='unique_match_pair_reverse-option_b_ind'), models.UniqueConstraint(fields=('question', 'option_b', 'option_a_en'), name='unique_match_pair_reverse-option_a_en'), models.UniqueConstraint(fields=('question', 'option_b', 'option_a_ru'), name='unique_match_pair_reverse-option_a_ru'), models.UniqueConstraint(fields=('question', 'option_b', 'option_a_zh_hans'), name='unique_match_pair_reverse-option_a_zh_hans'), models.UniqueConstraint(fields=('question', 'option_b', 'option_a_zh_hant'), name='unique_match_pair_reverse-option_a_zh_hant'), models.UniqueConstraint(fields=('question', 'option_b', 'option_a_ja'), name='unique_match_pair_reverse-option_a_ja'), models.UniqueConstraint(fields=('question', 'option_b', 'option_a_ko'), name='unique_match_pair_reverse-option_a_ko'), models.UniqueConstraint(fields=('question', 'option_b', 'option_a_es'), name='unique_match_pair_reverse-option_a_es'), models.UniqueConstraint(fields=('question', 'option_b', 'option_a_pt'), name='unique_match_pair_reverse-option_a_pt'), models.UniqueConstraint(fields=('question', 'option_b', 'option_a_th'), name='unique_match_pair_reverse-option_a_th'), models.UniqueConstraint(fields=('question', 'option_b', 'option_a_vi'), name='unique_match_pair_reverse-option_a_vi'), models.UniqueConstraint(fields=('question', 'option_b', 'option_a_ind'), name='unique_match_pair_reverse-option_a_ind')],
            },
        ),
        migrations.CreateModel(
            name='MatchAnswerProgress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option_a', models.CharField()),
                ('option_b', models.CharField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(limit_choices_to={'question_type': 'MATCH'}, on_delete=django.db.models.deletion.CASCADE, related_name='answer_progress', to='quizzes.question')),
            ],
            options={
                'verbose_name': 'Match answer progress',
                'verbose_name_plural': 'Match answer progresses',
                'abstract': False,
                'unique_together': {('user', 'question', 'option_a', 'option_b')},
            },
        ),
        migrations.RunPython(create_answer_texts),
    ]
