# Generated by Django 5.2.4 on 2025-08-02 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'MCQ'), ('MATCH', 'Match option pairs'), ('YES_NO', 'Yes or No')]),
        ),
        migrations.CreateModel(
            name='YesNoAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_yes', models.BooleanField(verbose_name="Is 'Yes' the correct answer?")),
                ('question', models.OneToOneField(limit_choices_to={'question_type': 'YES_NO'}, on_delete=django.db.models.deletion.CASCADE, related_name='yes_no_answer', to='quizzes.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Yes/No answer',
                'verbose_name_plural': 'Yes/No answers',
                'abstract': False,
            },
        ),
    ]
