# Generated by Django 5.2.4 on 2025-08-03 12:21

from django.db import migrations, models

def create_yes_no_texts(apps, schema_editor):
    Text = apps.get_model('quizzes', 'Text')
    Text.objects.get_or_create(key="yes", text="Yeah!")
    Text.objects.get_or_create(key="no", text="Nope.")


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_question_question_type_yesnoanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'MCQ'), ('MATCH', 'Match option pairs'), ('YES_NO', 'Yes or no')]),
        ),
        migrations.RunPython(create_yes_no_texts),
    ]
