# Generated by Django 5.2.4 on 2025-08-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_question_question_type_yesnoanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'MCQ'), ('MATCH', 'Match option pairs'), ('YES_NO', 'Yes or no')]),
        ),
    ]
