# Generated by Django 5.2.4 on 2025-08-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='penalty_points',
            field=models.IntegerField(default=20, verbose_name='Penalty points'),
        ),
        migrations.AddField(
            model_name='yesnoanswer',
            name='statement',
            field=models.TextField(blank=True, default='', verbose_name='Statement'),
        ),
        migrations.AddField(
            model_name='yesnoanswer',
            name='statement_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Statement'),
        ),
        migrations.AddField(
            model_name='yesnoanswer',
            name='statement_es',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Statement'),
        ),
        migrations.AddField(
            model_name='yesnoanswer',
            name='statement_ind',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Statement'),
        ),
        migrations.AddField(
            model_name='yesnoanswer',
            name='statement_ja',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Statement'),
        ),
        migrations.AddField(
            model_name='yesnoanswer',
            name='statement_ko',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Statement'),
        ),
        migrations.AddField(
            model_name='yesnoanswer',
            name='statement_pt',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Statement'),
        ),
        migrations.AddField(
            model_name='yesnoanswer',
            name='statement_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Statement'),
        ),
        migrations.AddField(
            model_name='yesnoanswer',
            name='statement_th',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Statement'),
        ),
        migrations.AddField(
            model_name='yesnoanswer',
            name='statement_vi',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Statement'),
        ),
        migrations.AddField(
            model_name='yesnoanswer',
            name='statement_zh_hans',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Statement'),
        ),
        migrations.AddField(
            model_name='yesnoanswer',
            name='statement_zh_hant',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Statement'),
        ),
    ]
