# Generated by Django 5.2.4 on 2025-09-16 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_quizquestion_penalty_points_yesnoanswer_statement_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Text',
        ),
    ]
