# Generated by Django 5.2.4 on 2025-07-22 17:35

import django.db.models.deletion
from django.db import migrations, models


def create_welcome_text(apps, schema_editor):
    Text = apps.get_model('users', 'Text')
    Text.objects.get_or_create(key="welcome", text="Welcome!")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(unique=True)),
                ('name_en', models.CharField(null=True, unique=True)),
                ('name_ru', models.CharField(null=True, unique=True)),
                ('name_zh_hans', models.CharField(null=True, unique=True)),
                ('name_zh_hant', models.CharField(null=True, unique=True)),
                ('name_ja', models.CharField(null=True, unique=True)),
                ('name_ko', models.CharField(null=True, unique=True)),
                ('name_es', models.CharField(null=True, unique=True)),
                ('name_pt', models.CharField(null=True, unique=True)),
                ('name_th', models.CharField(null=True, unique=True)),
                ('name_vi', models.CharField(null=True, unique=True)),
                ('name_ind', models.CharField(null=True, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='', null=True)),
                ('description_ru', models.TextField(blank=True, default='', null=True)),
                ('description_zh_hans', models.TextField(blank=True, default='', null=True)),
                ('description_zh_hant', models.TextField(blank=True, default='', null=True)),
                ('description_ja', models.TextField(blank=True, default='', null=True)),
                ('description_ko', models.TextField(blank=True, default='', null=True)),
                ('description_es', models.TextField(blank=True, default='', null=True)),
                ('description_pt', models.TextField(blank=True, default='', null=True)),
                ('description_th', models.TextField(blank=True, default='', null=True)),
                ('description_vi', models.TextField(blank=True, default='', null=True)),
                ('description_ind', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'verbose_name': 'Business unit',
                'verbose_name_plural': 'Business units',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(unique=True)),
                ('text', models.TextField(blank=True, default='')),
                ('text_en', models.TextField(blank=True, default='', null=True)),
                ('text_ru', models.TextField(blank=True, default='', null=True)),
                ('text_zh_hans', models.TextField(blank=True, default='', null=True)),
                ('text_zh_hant', models.TextField(blank=True, default='', null=True)),
                ('text_ja', models.TextField(blank=True, default='', null=True)),
                ('text_ko', models.TextField(blank=True, default='', null=True)),
                ('text_es', models.TextField(blank=True, default='', null=True)),
                ('text_pt', models.TextField(blank=True, default='', null=True)),
                ('text_th', models.TextField(blank=True, default='', null=True)),
                ('text_vi', models.TextField(blank=True, default='', null=True)),
                ('text_ind', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'verbose_name': 'Text',
                'verbose_name_plural': 'Texts',
                'abstract': False,
            },
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.businessunit'),
        ),
        migrations.RunPython(create_welcome_text),
    ]
