# Generated by Django 5.2.4 on 2025-07-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_businessunit_text_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='highest_score_quizzes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='times_played_quizzes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_seconds_at_highest_score_quizzes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
