# Generated by Django 5.2.4 on 2025-07-29 11:23

from django.db import migrations, models

def create_default_email_domain(apps, schema_editor):
    EmailDomain = apps.get_model('users', 'EmailDomain')
    EmailDomain.objects.get_or_create(domain="amway.com")

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_highest_score_quizzes_user_times_played_quizzes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDomain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(unique=True)),
            ],
            options={
                'verbose_name': 'Email domain',
                'verbose_name_plural': 'Email domains',
                'abstract': False,
            },
        ),
        migrations.RunPython(create_default_email_domain),
    ]
