# Generated by Django 5.2.4 on 2025-07-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_emaildomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_score_quizzes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_questions_answered_this_session',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
