# Generated by Django 5.2.4 on 2025-08-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_current_score_quizzes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_score_quizzes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
