# Generated by Django 5.2.4 on 2025-09-16 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_total_score_quizzes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Text',
        ),
    ]
