# Generated by Django 5.2.4 on 2025-10-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_delete_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='best_total_seconds_fake_boss',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_score_fake_boss',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_seconds_fake_boss',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
