# Generated by Django 5.2.4 on 2025-10-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_best_total_seconds_fake_boss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_score_phishing',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='highest_score_phishing',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='times_played_phishing',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_score_phishing',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_seconds_at_highest_score_phishing',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
