# Generated by Django 5.2.4 on 2025-11-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_current_score_phishing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_score_phishing',
            field=models.IntegerField(default=0),
        ),
    ]
