# Generated by Django 5.2.4 on 2025-09-23 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(verbose_name='Question text')),
                ('text_en', models.TextField(null=True, verbose_name='Question text')),
                ('text_ru', models.TextField(null=True, verbose_name='Question text')),
                ('text_zh_hans', models.TextField(null=True, verbose_name='Question text')),
                ('text_zh_hant', models.TextField(null=True, verbose_name='Question text')),
                ('text_ja', models.TextField(null=True, verbose_name='Question text')),
                ('text_ko', models.TextField(null=True, verbose_name='Question text')),
                ('text_es', models.TextField(null=True, verbose_name='Question text')),
                ('text_pt', models.TextField(null=True, verbose_name='Question text')),
                ('text_th', models.TextField(null=True, verbose_name='Question text')),
                ('text_vi', models.TextField(null=True, verbose_name='Question text')),
                ('text_ind', models.TextField(null=True, verbose_name='Question text')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(verbose_name='Option text')),
                ('text_en', models.CharField(null=True, verbose_name='Option text')),
                ('text_ru', models.CharField(null=True, verbose_name='Option text')),
                ('text_zh_hans', models.CharField(null=True, verbose_name='Option text')),
                ('text_zh_hant', models.CharField(null=True, verbose_name='Option text')),
                ('text_ja', models.CharField(null=True, verbose_name='Option text')),
                ('text_ko', models.CharField(null=True, verbose_name='Option text')),
                ('text_es', models.CharField(null=True, verbose_name='Option text')),
                ('text_pt', models.CharField(null=True, verbose_name='Option text')),
                ('text_th', models.CharField(null=True, verbose_name='Option text')),
                ('text_vi', models.CharField(null=True, verbose_name='Option text')),
                ('text_ind', models.CharField(null=True, verbose_name='Option text')),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='fake_boss.question')),
            ],
            options={
                'verbose_name': 'Answer option',
                'verbose_name_plural': 'Answer options',
                'abstract': False,
            },
        ),
    ]
