# Generated by Django 5.2.4 on 2025-09-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake_boss', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text_es',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text_ind',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text_ja',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text_ko',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text_pt',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text_th',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text_vi',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text_zh_hans',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text_zh_hant',
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.TextField(default='', verbose_name='Question title'),
        ),
        migrations.AddField(
            model_name='question',
            name='title_en',
            field=models.TextField(default='', null=True, verbose_name='Question title'),
        ),
        migrations.AddField(
            model_name='question',
            name='title_es',
            field=models.TextField(default='', null=True, verbose_name='Question title'),
        ),
        migrations.AddField(
            model_name='question',
            name='title_ind',
            field=models.TextField(default='', null=True, verbose_name='Question title'),
        ),
        migrations.AddField(
            model_name='question',
            name='title_ja',
            field=models.TextField(default='', null=True, verbose_name='Question title'),
        ),
        migrations.AddField(
            model_name='question',
            name='title_ko',
            field=models.TextField(default='', null=True, verbose_name='Question title'),
        ),
        migrations.AddField(
            model_name='question',
            name='title_pt',
            field=models.TextField(default='', null=True, verbose_name='Question title'),
        ),
        migrations.AddField(
            model_name='question',
            name='title_ru',
            field=models.TextField(default='', null=True, verbose_name='Question title'),
        ),
        migrations.AddField(
            model_name='question',
            name='title_th',
            field=models.TextField(default='', null=True, verbose_name='Question title'),
        ),
        migrations.AddField(
            model_name='question',
            name='title_vi',
            field=models.TextField(default='', null=True, verbose_name='Question title'),
        ),
        migrations.AddField(
            model_name='question',
            name='title_zh_hans',
            field=models.TextField(default='', null=True, verbose_name='Question title'),
        ),
        migrations.AddField(
            model_name='question',
            name='title_zh_hant',
            field=models.TextField(default='', null=True, verbose_name='Question title'),
        ),
    ]
