# Generated by Django 5.2.4 on 2025-09-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake_boss', '0002_remove_question_text_remove_question_text_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Answer label', 'verbose_name_plural': 'Answer labels'},
        ),
        migrations.AddField(
            model_name='answer',
            name='bee_safe_text',
            field=models.CharField(default='', verbose_name='Bee Safe text'),
        ),
        migrations.AddField(
            model_name='answer',
            name='bee_safe_text_en',
            field=models.CharField(default='', null=True, verbose_name='Bee Safe text'),
        ),
        migrations.AddField(
            model_name='answer',
            name='bee_safe_text_es',
            field=models.CharField(default='', null=True, verbose_name='Bee Safe text'),
        ),
        migrations.AddField(
            model_name='answer',
            name='bee_safe_text_ind',
            field=models.CharField(default='', null=True, verbose_name='Bee Safe text'),
        ),
        migrations.AddField(
            model_name='answer',
            name='bee_safe_text_ja',
            field=models.CharField(default='', null=True, verbose_name='Bee Safe text'),
        ),
        migrations.AddField(
            model_name='answer',
            name='bee_safe_text_ko',
            field=models.CharField(default='', null=True, verbose_name='Bee Safe text'),
        ),
        migrations.AddField(
            model_name='answer',
            name='bee_safe_text_pt',
            field=models.CharField(default='', null=True, verbose_name='Bee Safe text'),
        ),
        migrations.AddField(
            model_name='answer',
            name='bee_safe_text_ru',
            field=models.CharField(default='', null=True, verbose_name='Bee Safe text'),
        ),
        migrations.AddField(
            model_name='answer',
            name='bee_safe_text_th',
            field=models.CharField(default='', null=True, verbose_name='Bee Safe text'),
        ),
        migrations.AddField(
            model_name='answer',
            name='bee_safe_text_vi',
            field=models.CharField(default='', null=True, verbose_name='Bee Safe text'),
        ),
        migrations.AddField(
            model_name='answer',
            name='bee_safe_text_zh_hans',
            field=models.CharField(default='', null=True, verbose_name='Bee Safe text'),
        ),
        migrations.AddField(
            model_name='answer',
            name='bee_safe_text_zh_hant',
            field=models.CharField(default='', null=True, verbose_name='Bee Safe text'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(verbose_name='Label text'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text_en',
            field=models.CharField(null=True, verbose_name='Label text'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text_es',
            field=models.CharField(null=True, verbose_name='Label text'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text_ind',
            field=models.CharField(null=True, verbose_name='Label text'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text_ja',
            field=models.CharField(null=True, verbose_name='Label text'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text_ko',
            field=models.CharField(null=True, verbose_name='Label text'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text_pt',
            field=models.CharField(null=True, verbose_name='Label text'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text_ru',
            field=models.CharField(null=True, verbose_name='Label text'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text_th',
            field=models.CharField(null=True, verbose_name='Label text'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text_vi',
            field=models.CharField(null=True, verbose_name='Label text'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text_zh_hans',
            field=models.CharField(null=True, verbose_name='Label text'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text_zh_hant',
            field=models.CharField(null=True, verbose_name='Label text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(default='', verbose_name='Question title'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title_en',
            field=models.CharField(default='', null=True, verbose_name='Question title'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title_es',
            field=models.CharField(default='', null=True, verbose_name='Question title'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title_ind',
            field=models.CharField(default='', null=True, verbose_name='Question title'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title_ja',
            field=models.CharField(default='', null=True, verbose_name='Question title'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title_ko',
            field=models.CharField(default='', null=True, verbose_name='Question title'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title_pt',
            field=models.CharField(default='', null=True, verbose_name='Question title'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title_ru',
            field=models.CharField(default='', null=True, verbose_name='Question title'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title_th',
            field=models.CharField(default='', null=True, verbose_name='Question title'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title_vi',
            field=models.CharField(default='', null=True, verbose_name='Question title'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title_zh_hans',
            field=models.CharField(default='', null=True, verbose_name='Question title'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title_zh_hant',
            field=models.CharField(default='', null=True, verbose_name='Question title'),
        ),
    ]
