# Generated by Django 5.2.4 on 2025-10-08 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhishingAnnotatedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='phishing_emails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhishingGameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('total_time', models.FloatField(help_text='seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='phishing.phishingannotatedemail')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-score', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='PhishingIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x1', models.FloatField(help_text='Normalized left (0..1)')),
                ('y1', models.FloatField(help_text='Normalized top (0..1)')),
                ('x2', models.FloatField(help_text='Normalized right (0..1)')),
                ('y2', models.FloatField(help_text='Normalized bottom (0..1)')),
                ('label', models.CharField(help_text='Label text for this indicator', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='phishing.phishingannotatedemail')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
