# Generated by Django 5.2.4 on 2025-11-03 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phishing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhishingGameResult',
        ),
    ]
