# Generated by Django 5.2.4 on 2025-11-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishing', '0002_delete_phishinggameresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='phishingindicator',
            name='label_en',
            field=models.CharField(help_text='Label text for this indicator', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='phishingindicator',
            name='label_es',
            field=models.CharField(help_text='Label text for this indicator', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='phishingindicator',
            name='label_ind',
            field=models.CharField(help_text='Label text for this indicator', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='phishingindicator',
            name='label_ja',
            field=models.CharField(help_text='Label text for this indicator', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='phishingindicator',
            name='label_ko',
            field=models.CharField(help_text='Label text for this indicator', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='phishingindicator',
            name='label_pt',
            field=models.CharField(help_text='Label text for this indicator', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='phishingindicator',
            name='label_ru',
            field=models.CharField(help_text='Label text for this indicator', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='phishingindicator',
            name='label_th',
            field=models.CharField(help_text='Label text for this indicator', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='phishingindicator',
            name='label_vi',
            field=models.CharField(help_text='Label text for this indicator', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='phishingindicator',
            name='label_zh_hans',
            field=models.CharField(help_text='Label text for this indicator', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='phishingindicator',
            name='label_zh_hant',
            field=models.CharField(help_text='Label text for this indicator', max_length=200, null=True),
        ),
    ]
