# Generated by Django 5.2.4 on 2025-11-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishing', '0003_phishingindicator_label_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phishingindicator',
            name='x1',
            field=models.FloatField(default=0.0, help_text='Normalized left (0..1)'),
        ),
        migrations.AlterField(
            model_name='phishingindicator',
            name='x2',
            field=models.FloatField(default=0.0, help_text='Normalized right (0..1)'),
        ),
        migrations.AlterField(
            model_name='phishingindicator',
            name='y1',
            field=models.FloatField(default=0.0, help_text='Normalized top (0..1)'),
        ),
        migrations.AlterField(
            model_name='phishingindicator',
            name='y2',
            field=models.FloatField(default=0.0, help_text='Normalized bottom (0..1)'),
        ),
    ]
