# Generated by Django 5.2.4 on 2025-11-06 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishing', '0004_alter_phishingindicator_x1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phishingannotatedemail',
            options={'ordering': ('id',), 'verbose_name': 'Phishing annotated email', 'verbose_name_plural': 'Phishing annotated emails'},
        ),
        migrations.AlterModelOptions(
            name='phishingindicator',
            options={'ordering': ('id',), 'verbose_name': 'Phishing indicator', 'verbose_name_plural': 'Phishing indicators'},
        ),
        migrations.AddField(
            model_name='phishingannotatedemail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='phishingindicator',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='phishingannotatedemail',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='phishingindicator',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='PhishingAnnotatedEmailAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.IntegerField(default=0)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phishing.phishingannotatedemail')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phishing.phishingindicator')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phishing email answer',
                'verbose_name_plural': 'Phishing email answers',
                'abstract': False,
                'unique_together': {('email', 'user')},
            },
        ),
    ]
