# Generated by Django 5.2.4 on 2025-11-06 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phishing', '0005_alter_phishingannotatedemail_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='phishingannotatedemailanswer',
            unique_together=set(),
        ),
    ]
