# Generated by Django 5.2.4 on 2025-11-06 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phishing', '0006_alter_phishingannotatedemailanswer_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phishingannotatedemail',
            options={'ordering': ('id',), 'verbose_name': 'Phishing email', 'verbose_name_plural': 'Phishing emails'},
        ),
        migrations.AlterModelOptions(
            name='phishingannotatedemailanswer',
            options={'verbose_name': 'Submitted indicator', 'verbose_name_plural': 'Submitted indicators'},
        ),
    ]
